version: '3'
services:
  movies:  
    image: vijay3518/moviesrepopaytm:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: vijay3518/trainrepopaytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: vijay3518/dthrepopaytm:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: vijay3518/rechargerepopaytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
